### ISSUE TITLE
K8S deployment failed, executable file not found in $PATH

### ISSUE THREAD

**Issue by Caelebs** [iGeeky/wolf#2]
When deploying in k8s, the startup fails with an error message
```
Error: failed to start container "container-6harf2": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"npm run start\": executable file not found in $PATH": unknown
```
The configuration file is created according to the **docker-compose.yaml** in the **quick-start-with-docker** directory
```
containers:
        - name: container-6harf2
          image: igeeky/wolf-server
          command:
            - npm run start
          ports:
            - name: http-10080
              containerPort: 10080
              protocol: TCP
          env:
            - name: RBAC_ROOT_PASSWORD
              value: wolf-123456
            - name: RBAC_TOKEN_KEY
              value: f40215a5f25cbb6d36df07629aaf1172240fe48d
            - name: WOLF_CRYPT_KEY
              value: fbd4962351924792cb5e5b131435cd30b24e3570
            - name: RBAC_SQL_URL
              value: 'postgres://root:123456@wolf-database:5432/wolf'
            - name: CLIENT_CHANGE_PWD
              value: '"no"'
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 10Mi
          volumeMounts:
            - name: volume-bhm8gz
              mountPath: /data/www
```

**Comment by iGeeky** [comment]
I'm sorry, but I haven't tested running wolf on k8s yet, since I haven't used k8s before. 
But as I see above, there may be a problem with the command (based on docker-compose experience), try changing the command to something like this: 
`command: ["npm", "run", "start"]`

**Comment by Caelebs** [comment]
I tried it but the problem still exists, It seems that there is nothing wrong with the configuration file, I will try to find other ways.
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  53s                default-scheduler  Successfully assigned wolf/wolf-server-tj7ogt-78b454dcf9-n9pnj to node06
  Warning  BackOff    23s (x2 over 50s)  kubelet, node06    Back-off restarting failed container
  Normal   Pulled     10s (x4 over 52s)  kubelet, node06    Container image "igeeky/wolf-server" already present on machine
  Normal   Created    10s (x4 over 52s)  kubelet, node06    Created container wolf-server
  Warning  Failed     10s (x4 over 51s)  kubelet, node06    Error: failed to start container "wolf-server": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"[\\\"npm\\\", \\\"run\\\", \\\"start\\\"]\": executable file not found in $PATH": unknown
```

@iGeeky

**Comment by iGeeky** [comment]
You can refer to the following documentation: 
```
https://unofficial-kubernetes.readthedocs.io/en/latest/concepts/configuration/container-command-args/
```
Using command with args. like this:
```
 command: ["npm"]
 args: ["run", "start"]
```

**Comment by Caelebs** [comment]
Perfect solution! I deployed it like this, the service can be started.
```
spec:
      containers:
        - name: container-06s18q
          image: igeeky/wolf-server
          **command:
            - npm
          args:
            - run
            - start**
          ports:
            - name: http-10080
              containerPort: 10080
              protocol: TCP
          env:
            - name: RBAC_ROOT_PASSWORD
              value: wolf-123456
            - name: RBAC_TOKEN_KEY
              value: f40215a5f25cbb6d36df07629aaf1172240fe48d
            - name: WOLF_CRYPT_KEY
              value: fbd4962351924792cb5e5b131435cd30b24e3570
            - name: RBAC_SQL_URL
              value: 'postgres://root:123456@wolf-database:5432/wolf'
            - name: CLIENT_CHANGE_PWD
              value: 'no'
```
Thanks for your help
@iGeeky
